version: "3"

services:
  mdparser:
    image: markdown-parser
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    ports:
        - "8787:80"
    volumes:
        - ./frontend:/usr/local/apache2/htdocs/

  gcp-deploy:
    image: gcp-deploy
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    volumes:
      - ./backend:/var/code